all:
	antlr4 -Dlanguage=Python3 -visitor -listener *.g4

clean:
	rm -f nasm_x86_64_Lexer.interp nasm_x86_64_Lexer.py nasm_x86_64_Lexer.tokens nasm_x86_64_Parser.interp nasm_x86_64_Parser.tokens nasm_x86_64_ParserVisitor.py nasm_x86_64_ParserListener.py nasm_x86_64_Parser.py
